//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanopusAirlines.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public int flight_id { get; set; }
        public Nullable<int> departure_id { get; set; }
        public Nullable<int> arrival_id { get; set; }
        public Nullable<System.DateTime> flight_date { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> price_business { get; set; }
        public string flight_number { get; set; }
        public Nullable<int> available_seats { get; set; }
    }
}
