//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanopusAirlines.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CanopusAirportsEntities : DbContext
    {
        public CanopusAirportsEntities()
            : base("name=CanopusAirportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airports> Airports { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
    
        public virtual int sp_AddNewAirport(string name, string city, string country, string iata)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var iataParameter = iata != null ?
                new ObjectParameter("Iata", iata) :
                new ObjectParameter("Iata", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddNewAirport", nameParameter, cityParameter, countryParameter, iataParameter);
        }
    
        public virtual ObjectResult<sp_SearchFlights_Result> sp_SearchFlights(Nullable<int> departureID, Nullable<int> arrivalID, Nullable<System.DateTime> date, string classType)
        {
            var departureIDParameter = departureID.HasValue ?
                new ObjectParameter("DepartureID", departureID) :
                new ObjectParameter("DepartureID", typeof(int));
    
            var arrivalIDParameter = arrivalID.HasValue ?
                new ObjectParameter("ArrivalID", arrivalID) :
                new ObjectParameter("ArrivalID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var classTypeParameter = classType != null ?
                new ObjectParameter("ClassType", classType) :
                new ObjectParameter("ClassType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchFlights_Result>("sp_SearchFlights", departureIDParameter, arrivalIDParameter, dateParameter, classTypeParameter);
        }
    }
}
