//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanopusAirlines.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ticket_id { get; set; }
        public Nullable<int> flight_id { get; set; }
        public Nullable<int> passenger_id { get; set; }
        public string seat_number { get; set; }
        public string pnr_code { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<System.DateTime> booking_date { get; set; }
    
        public virtual Flights Flights { get; set; }
        public virtual Passengers Passengers { get; set; }
    }
}
